In [88]:
import numpy as np
import pandas as pd

In [89]:
# loading the data
df = pd.read_csv(r"anime.csv")
# writing path can activate escape sequence
# placed 'r' to overcome this
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [90]:
df.loc[1]

Rank                                                     2
Title    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
Score                                                 9.07
Name: 1, dtype: object

In [91]:
df.loc[1]['Title']
# every title has episode count
# no separate column, lets make it

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

Feature extraction

In [92]:
def extract_episodes(txt):
    check = False
    data = ""
    for i in txt:
        if i == ')':
            return data 
        if check == True:
            data += i     
        if i == '(':
            check = True

In [93]:
df["Episodes"] = df['Title'].apply(extract_episodes)
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

In [94]:
# remove eps
df['Episodes'] = df['Episodes'].str.replace(" eps", "")
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

In [95]:
# convert  episodes string type -> integer type
df.loc[0]['Episodes']

'64'

In [96]:
df['Episodes'] = df['Episodes'].astype(int)
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

In [97]:
type(df.loc[0]['Episodes'])

numpy.int64

## Questions

In [98]:
# make a new column for timestamp
df.loc[3]['Title']

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

In [99]:
def extract_timestamp(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i] == ')':
            for j in range(i+1, i+20):
                data += txt[j]
    return data

In [100]:
# make a column for no of months
from datetime import datetime
def extract_months(txt):

    start, end = txt.split(" - ")

    start_date = datetime.strptime(start, "%b %Y")
    end_date = datetime.strptime(end, "%b %Y")

    months = (end_date.year - start_date.year) * 12 + (end_date.month - start_date.month)

    return months

In [104]:
df["Timestamps"] = df['Title'].apply(extract_timestamp)
df.head()

,Rank,Title,Score,Episodes,Timestamps
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [105]:
type(df.loc[0]['Timestamps'])

str

In [107]:
df['Months'] = df['Timestamps'].apply(extract_months).astype(int)
df.head()

,Rank,Title,Score,Episodes,Timestamps,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [108]:
type(df.loc[0]['Months'])

numpy.int64

In [109]:
# which anime has highest score
df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

In [110]:
# top 5 highest scoring anime
df['Title'].head(5)

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

In [113]:
df['Episodes'].max()

np.int64(201)

In [114]:
df['Episodes'].dtype

dtype('int64')

In [111]:
# which anime has highest episode count
df[df['Episodes'] == df['Episodes'].max()]['Title']

15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
Name: Title, dtype: str

In [112]:
# animes with top 5 episode count
df.sort_values(by='Episodes', ascending=False)[['Title', 'Episodes']].head()

                                                Title  Episodes
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201
7   Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...       148
11  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...       110
42  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...        75
24  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...        74

In [119]:
# which is the longest running anime
df[df['Months']== df['Months'].max()]['Title']

11    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
Name: Title, dtype: str