### Pandas

- is a 1-d labelled array capable of holding any data type
- the axis labels are collectively called the index

### Creating series

In [3]:
import numpy as np
import pandas as pd

- labels are called index here..

In [4]:
labels = ['a', 'b', 'c'] # labels
my_list = [10,20,30] # list
arr = np.array([10,20,30]) # array
d = {1:10, 2:20} # dict

In [8]:
pd.Series(my_list)
# labels/index | values/datapoints

0    10
1    20
2    30
dtype: int64

In [9]:
# setting custom labels
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [11]:
# can we create Series with an array
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

- series are 1d so you must keep array as vectors (1d)
- in case of dict, labels are defined itself using key

### DataFrames

- combination of series is called dataframes

1. Creating a dataframe

In [14]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [16]:
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df

In [23]:
# dataframe of a list
# 2d array
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

2. Selection and Indexing of columns

In [24]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [25]:
# targetting 2 columns at once
df2[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

3. Creating a new columns

In [28]:
df2['Designation'] = ["Doctor", "Engineer", "Tailor", "Clerk"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Tailor
3  Linda   42    London   85000       Clerk

4. Removing columns

In [33]:
df2.drop('Designation', axis =1, inplace=True) # check the columns
df2 # shows designation

# inplace -> keyword used to remove the dropped data in reality

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

5. Selecting a row

In [35]:
df.loc[0]

Name               John
Age                  28
City           New York
Salary            65000
Designation      Doctor
Name: 0, dtype: object

# selecting mutiple rows
df.loc[[0,1]]

In [37]:
# iloc -> indexed location
df.iloc[3]

Name            Linda
Age                42
City           London
Salary          85000
Designation     Clerk
Name: 3, dtype: object

6. Subset of rows and columns

In [38]:
# selecting specific roes and columns
df.loc[[0,1]][["City", "Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [39]:
# test
df.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

7. Conditional selection

In [41]:
# i want to those people whose age is above 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [47]:
# i want to those people whose age is above 30 and city must be paris
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

# here we use & -> for and operator
# and | -> for or operator

   Name  Age   City  Salary
1  Anna   34  Paris   70000